# Generated by Django 4.1.6 on 2023-02-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='arabic_name',
            new_name='ar_name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='english_name',
            new_name='en_name',
        ),
    ]
