# Generated by Django 4.2.1 on 2023-06-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines_api', '0002_rename_arabic_name_medicine_ar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
